EXCEPTION_STATUSBAR = "background-color: #FF0000"
FILE_ENTRE = './Designs/start.ui'
ENTRE_TITLE = 'Вход'
ENTER_PASSWORD = 'Введите пароль'
ENTER_LOGIN = 'Введите логин'
ENTER_LOGIN_PASSWORD = 'Введите логин и пароль'
EXCEPTION_PASSWORD = 'Неверный пароль'
EXCEPTION_LOGIN = 'Нет пользователя с таким логином'
EMPTY_LINE = ''
LOGIN_EXIST = 'Пользователь с таким логином уже существует'
FILE_REGISTRATION = './Designs/registration.ui'
REGISTRATION_TITLE = 'Регистрация'
FILE_CARDS = './Designs/cards.ui'
CARDS_TITLE = 'Карточки'
BTN_COLOR = "background-color: grey; border: 0.5; font-size: 30px; color: white"
BTN_RED = "background-color: red; border: 0.5; font-size: 30px; color: white"
END = 'Слова закончились!'
START_STATUSBAR = 100
FILE_WORDS = './Designs/words.ui'
WORDS_TITLE = 'Все слова'
IMAGE = './Designs/logo.png'
IMAGE_RESIZED = 'resized.logo.png'
FONT_CHECKBOX = 'font-size: 30px'
SPACE_BETWEEN_COLUMNS = 230
NEW_SIZE_IMAGE = (300, 100)
ALL_WORDS_AMOUNT = 476