EXCEPTION_STATUSBAR = "background-color: #FF0000"
FILE_ENTRE = '../Designs/start.ui'
ENTRE_TITLE = 'Вход'
ENTER_PASSWORD = 'Введите пароль'
ENTER_LOGIN = 'Введите логин'
ENTER_LOGIN_PASSWORD = 'Введите логин и пароль'
EXCEPTION_PASSWORD = 'Неверный пароль'
EXCEPTION_LOGIN = 'Нет пользователя с таким логином'
EMPTY_LINE = ''
LOGIN_EXIST = 'Пользователь с таким логином уже существует'
FILE_REGISTRATION = '../Designs/registration.ui'
REGISTRATION_TITLE = 'Регистрация'
FILE_CARDS = '../Designs/cards.ui'
CARDS_TITLE = 'Карточки'
BTN_RED = "background-color: red; border: 0.5; font-size: 30px; color: white"
END = 'Слова закончились!'
START_STATUSBAR = 100
FILE_WORDS = '../Designs/words.ui'
WORDS_TITLE = 'Все слова'
IMAGE = '../Designs/logo.png'
IMAGE_RESIZED = 'resized.logo.png'
FONT_CHECKBOX = 'font-size: 30px'
SPACE_BETWEEN_COLUMNS = 300
NEW_SIZE_IMAGE = (300, 100)
ALL_WORDS_AMOUNT = 476
BTN_GREY = "background-color: grey; border: 0.5; font-size: 30px; color: white"
FILE_TEST = '../Designs/test.ui'
TEST_TITLE = 'Тест'
BTN_ORANGE = "background-color: orange; border: 50%; font-size: 30px; color: white"
MSGBOX_TITLE = 'Инструкция'
INSTRUCTION = ('Отметьте слово галочкой, чтобы добавить его в "Избранные"\n'
                    'Или уберите галочку, чтобы удалить слово из "Избранных".\n'
                    'При выходе назад данные сохранятся.')
INSTRUCTION_FAVOURITES = 'Уберите галочку, чтобы убрать слово из избранных.\n При выходе назад данные сохранятся.'
BTN_CARDS_FAVOURITE_STYLE = 'background-color: #3399cc; border: 50%; font-size: 20px; color: white'
BTN_CARDS_FAVOURITE_TEXT = 'Заучивание'
# FILE_FAVOURITE_CARDS = '../Designs/favourite_cards.ui'
LBL_WORD_CHOSE_AMOUNT = 'Выберите количество вопросов'