EXCEPTION_STATUSBAR = "background-color: #FF0000"
FILE_ENTRE = '../Designs/start.ui'
ENTRE_TITLE = 'Вход'
ENTER_PASSWORD = 'Введите пароль'
ENTER_LOGIN = 'Введите логин'
ENTER_LOGIN_PASSWORD = 'Введите логин и пароль'
EXCEPTION_PASSWORD = 'Неверный пароль'
EXCEPTION_LOGIN = 'Нет пользователя с таким логином'
EMPTY_LINE = ''
LOGIN_EXIST = 'Пользователь с таким логином уже существует'
FILE_REGISTRATION = '../Designs/registration.ui'
REGISTRATION_TITLE = 'Регистрация'
FILE_CARDS = '../Designs/cards.ui'
CARDS_TITLE = 'Карточки'
BTN_RED = "background-color: rgba(255,38,0,41); border: 0.5; font-size: 30px; color: white"
END = 'Слова закончились!'
START_PROGRESSBAR = 100
FILE_WORDS = '../Designs/words.ui'
WORDS_TITLE = 'Все слова'
IMAGE = '../Designs/logo.png'
IMAGE_RESIZED = 'resized.logo.png'
FONT_CHECKBOX = 'font-size: 30px'
SPACE_BETWEEN_COLUMNS = 260
NEW_SIZE_IMAGE = (300, 100)
ALL_WORDS_AMOUNT = 476
BTN_GREY = "background-color: rgba(169,169,169,128); border: 0.5; font-size: 30px; color: white"
FILE_TEST = '../Designs/test.ui'
TEST_TITLE = 'Тест'
BTN_ORANGE = "background-color: rgba(255, 147, 0, 77); border: 50%; font-size: 30px; color: white"
MSGBOX_TITLE = 'Инструкция'
INSTRUCTION = ('Отметьте слово галочкой, чтобы добавить его в "Избранные"\n'
                    'Или уберите галочку, чтобы удалить слово из "Избранных".\n'
                    'При выходе назад данные сохранятся.')
INSTRUCTION_FAVOURITES = 'Уберите галочку, чтобы убрать слово из избранных.\n При выходе назад данные сохранятся.'
BTN_CARDS_FAVOURITE_STYLE = 'background-color: rgba(255,38,0,41); border: 50%; font-size: 20px; color: white'
BTN_CARDS_FAVOURITE_TEXT = 'Заучивание'
FILE_FAVOURITE_CARDS = '../Designs/favourites_cards.ui'
FAVOURITE_CARDS_TITLE = 'Заучивание избранных слов'
LBL_WORD_CHOOSE_AMOUNT = 'Выберите количество вопросов'
FILE_RESULTS = '../Designs/result.ui'
RESULTS_TITLE = 'Результаты теста'
INSTRUCTION_FAVOURITES_CARDS = 'При нажатии на кнопку "Усвоено" слово не будет удалено из избранных'