# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/young_cucumber/Desktop/help/favourites_cards.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgba(255, 212, 121, 128);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_back = QtWidgets.QPushButton(self.centralwidget)
        self.btn_back.setGeometry(QtCore.QRect(10, 10, 91, 41))
        self.btn_back.setStyleSheet("background-color: rgba(255, 147, 0, 128);\n"
"color: rgb(255, 255, 255);")
        self.btn_back.setObjectName("btn_back")
        self.btn_card = QtWidgets.QPushButton(self.centralwidget)
        self.btn_card.setGeometry(QtCore.QRect(210, 120, 361, 321))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btn_card.setFont(font)
        self.btn_card.setStyleSheet("background-color: rgba(169, 169, 169, 128);\n"
"color: rgb(255, 255, 255);")
        self.btn_card.setText("")
        self.btn_card.setObjectName("btn_card")
        self.lbl_logo = QtWidgets.QLabel(self.centralwidget)
        self.lbl_logo.setGeometry(QtCore.QRect(120, 10, 321, 91))
        self.lbl_logo.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lbl_logo.setText("")
        self.lbl_logo.setPixmap(QtGui.QPixmap("/Users/young_cucumber/Desktop/help/../Not programming code/logo.png"))
        self.lbl_logo.setObjectName("lbl_logo")
        self.btn_next = QtWidgets.QPushButton(self.centralwidget)
        self.btn_next.setGeometry(QtCore.QRect(610, 150, 131, 261))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_next.setFont(font)
        self.btn_next.setStyleSheet("background-color: rgba(255, 147, 0, 128);\n"
"color: rgb(255, 255, 255);")
        self.btn_next.setObjectName("btn_next")
        self.btn_complete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_complete.setGeometry(QtCore.QRect(40, 150, 131, 261))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_complete.setFont(font)
        self.btn_complete.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 144, 81, 128);")
        self.btn_complete.setObjectName("btn_complete")
        self.progressbr = QtWidgets.QProgressBar(self.centralwidget)
        self.progressbr.setGeometry(QtCore.QRect(10, 510, 781, 23))
        self.progressbr.setStyleSheet("background-color: rgba(255, 212, 121, 0);")
        self.progressbr.setProperty("value", 24)
        self.progressbr.setObjectName("progressbr")
        self.lbl_show = QtWidgets.QLabel(self.centralwidget)
        self.lbl_show.setGeometry(QtCore.QRect(230, 60, 371, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_show.setFont(font)
        self.lbl_show.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.lbl_show.setObjectName("lbl_show")
        self.btn_instruction = QtWidgets.QPushButton(self.centralwidget)
        self.btn_instruction.setGeometry(QtCore.QRect(650, 0, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_instruction.setFont(font)
        self.btn_instruction.setStyleSheet("background-color: rgba(0, 143, 0, 77);\n"
"color: rgb(255, 255, 255);")
        self.btn_instruction.setObjectName("btn_instruction")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_back.setText(_translate("MainWindow", "Назад"))
        self.btn_next.setText(_translate("MainWindow", "Следующее"))
        self.btn_complete.setText(_translate("MainWindow", "Усвоено"))
        self.lbl_show.setText(_translate("MainWindow", "Нажмите, чтобы посмотреть ответ"))
        self.btn_instruction.setText(_translate("MainWindow", "Инструкция"))
