# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/young_cucumber/Desktop/help/Designs/menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 569)
        MainWindow.setStyleSheet("background-color: rgba(255, 212, 121, 128);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_logo = QtWidgets.QLabel(self.centralwidget)
        self.lbl_logo.setGeometry(QtCore.QRect(-10, 10, 321, 81))
        self.lbl_logo.setStyleSheet("background-color: rgba(255, 147, 0, 8);")
        self.lbl_logo.setText("")
        self.lbl_logo.setPixmap(QtGui.QPixmap("/Users/young_cucumber/Desktop/help/Designs/../Not programming code/logo.png"))
        self.lbl_logo.setObjectName("lbl_logo")
        self.btn_words = QtWidgets.QPushButton(self.centralwidget)
        self.btn_words.setGeometry(QtCore.QRect(30, 310, 371, 191))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btn_words.setFont(font)
        self.btn_words.setStyleSheet("background-color: rgb(255, 212, 121);\n"
"color: rgb(255, 255, 255);")
        self.btn_words.setObjectName("btn_words")
        self.btn_favourites = QtWidgets.QPushButton(self.centralwidget)
        self.btn_favourites.setGeometry(QtCore.QRect(30, 110, 371, 191))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btn_favourites.setFont(font)
        self.btn_favourites.setStyleSheet("background-color: rgb(255, 212, 121);\n"
"color: rgb(255, 255, 255);")
        self.btn_favourites.setObjectName("btn_favourites")
        self.btn_cards = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cards.setGeometry(QtCore.QRect(410, 110, 371, 191))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btn_cards.setFont(font)
        self.btn_cards.setStyleSheet("background-color: rgb(255, 212, 121);\n"
"color: rgb(255, 255, 255);")
        self.btn_cards.setObjectName("btn_cards")
        self.btn_test = QtWidgets.QPushButton(self.centralwidget)
        self.btn_test.setGeometry(QtCore.QRect(410, 310, 371, 191))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btn_test.setFont(font)
        self.btn_test.setStyleSheet("background-color: rgb(255, 212, 121);\n"
"color: rgb(255, 255, 255);")
        self.btn_test.setObjectName("btn_test")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_words.setText(_translate("MainWindow", "ВСЕ СЛОВА"))
        self.btn_favourites.setText(_translate("MainWindow", "ИЗБРАННОЕ"))
        self.btn_cards.setText(_translate("MainWindow", "КАРТОЧКИ"))
        self.btn_test.setText(_translate("MainWindow", "ТЕСТ"))
