# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/young_cucumber/Desktop/help/result.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: rgba(255, 212, 121, 128);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrlarea_words = QtWidgets.QScrollArea(self.centralwidget)
        self.scrlarea_words.setGeometry(QtCore.QRect(-1, 60, 801, 441))
        self.scrlarea_words.setWidgetResizable(True)
        self.scrlarea_words.setObjectName("scrlarea_words")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 797, 437))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.tablewdgt = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.tablewdgt.setGeometry(QtCore.QRect(0, 0, 801, 441))
        self.tablewdgt.setObjectName("tablewdgt")
        self.tablewdgt.setColumnCount(3)
        self.tablewdgt.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablewdgt.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewdgt.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewdgt.setHorizontalHeaderItem(2, item)
        self.scrlarea_words.setWidget(self.scrollAreaWidgetContents)
        self.btn_menu = QtWidgets.QPushButton(self.centralwidget)
        self.btn_menu.setGeometry(QtCore.QRect(10, 10, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_menu.setFont(font)
        self.btn_menu.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 147, 0, 128);")
        self.btn_menu.setObjectName("btn_menu")
        self.lbl_res = QtWidgets.QLabel(self.centralwidget)
        self.lbl_res.setGeometry(QtCore.QRect(570, 520, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_res.setFont(font)
        self.lbl_res.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 38, 0);")
        self.lbl_res.setObjectName("lbl_res")
        self.ledit_total = QtWidgets.QLineEdit(self.centralwidget)
        self.ledit_total.setEnabled(True)
        self.ledit_total.setGeometry(QtCore.QRect(662, 511, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ledit_total.setFont(font)
        self.ledit_total.setStyleSheet("background-color: rgba(0,144,81,128);\n"
"color: rgb(255, 255, 255);")
        self.ledit_total.setObjectName("ledit_total")
        self.lbl_logo = QtWidgets.QLabel(self.centralwidget)
        self.lbl_logo.setGeometry(QtCore.QRect(110, 0, 271, 61))
        self.lbl_logo.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lbl_logo.setText("")
        self.lbl_logo.setPixmap(QtGui.QPixmap("/Users/young_cucumber/Desktop/help/../Not programming code/resized.logo.png"))
        self.lbl_logo.setObjectName("lbl_logo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tablewdgt.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ваш ответ"))
        item = self.tablewdgt.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Правильный ответ"))
        item = self.tablewdgt.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Балл"))
        self.btn_menu.setText(_translate("MainWindow", "Назад"))
        self.lbl_res.setText(_translate("MainWindow", "Результат"))
