# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/young_cucumber/Desktop/help/test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgba(255, 212, 121, 128);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(170, 250, 461, 251))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vrtcllayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vrtcllayout.setContentsMargins(0, 0, 0, 0)
        self.vrtcllayout.setObjectName("vrtcllayout")
        self.lbl_word = QtWidgets.QLabel(self.centralwidget)
        self.lbl_word.setGeometry(QtCore.QRect(150, 200, 481, 31))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_word.setFont(font)
        self.lbl_word.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgba(0, 143, 0, 128);")
        self.lbl_word.setObjectName("lbl_word")
        self.btn_menu = QtWidgets.QPushButton(self.centralwidget)
        self.btn_menu.setGeometry(QtCore.QRect(10, 10, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_menu.setFont(font)
        self.btn_menu.setStyleSheet("background-color: rgba(255, 147, 0, 128);\n"
"color: rgb(255, 255, 255);")
        self.btn_menu.setObjectName("btn_menu")
        self.progressbr = QtWidgets.QProgressBar(self.centralwidget)
        self.progressbr.setGeometry(QtCore.QRect(20, 510, 761, 23))
        self.progressbr.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.progressbr.setProperty("value", 24)
        self.progressbr.setObjectName("progressbr")
        self.lbl_logo = QtWidgets.QLabel(self.centralwidget)
        self.lbl_logo.setGeometry(QtCore.QRect(140, 10, 331, 91))
        self.lbl_logo.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lbl_logo.setText("")
        self.lbl_logo.setPixmap(QtGui.QPixmap("/Users/young_cucumber/Desktop/help/../../../.designer/backup/logo.png"))
        self.lbl_logo.setObjectName("lbl_logo")
        self.spnbox_amount = QtWidgets.QSpinBox(self.centralwidget)
        self.spnbox_amount.setGeometry(QtCore.QRect(610, 30, 171, 41))
        self.spnbox_amount.setStyleSheet("background-color: rgba(255,38,0,41);\n"
"color: rgb(255, 255, 255);")
        self.spnbox_amount.setMaximum(476)
        self.spnbox_amount.setObjectName("spnbox_amount")
        self.lbl_choose = QtWidgets.QLabel(self.centralwidget)
        self.lbl_choose.setGeometry(QtCore.QRect(530, 0, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lbl_choose.setFont(font)
        self.lbl_choose.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.lbl_choose.setObjectName("lbl_choose")
        self.btn_apply = QtWidgets.QPushButton(self.centralwidget)
        self.btn_apply.setGeometry(QtCore.QRect(700, 80, 81, 26))
        self.btn_apply.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(4,51,255,82);")
        self.btn_apply.setObjectName("btn_apply")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(179, 120, 441, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.lbl_logo_2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_logo_2.setGeometry(QtCore.QRect(120, 0, 321, 91))
        self.lbl_logo_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lbl_logo_2.setText("")
        self.lbl_logo_2.setPixmap(QtGui.QPixmap("/Users/young_cucumber/Desktop/help/../Not programming code/logo.png"))
        self.lbl_logo_2.setObjectName("lbl_logo_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_word.setText(_translate("MainWindow", "Выберите количество вопросов"))
        self.btn_menu.setText(_translate("MainWindow", "Назад"))
        self.lbl_choose.setText(_translate("MainWindow", "Выберите количество вопросов"))
        self.btn_apply.setText(_translate("MainWindow", "Применить"))
        self.label.setText(_translate("MainWindow", "Какой из вариантов ударения верный?"))
